language: node_js

sudo: false

node_js:
  - 14
  - 12
  - 10

os:
  - linux
  - osx
  - windows

install:
  - npm run setup

script:
  - npm run test:ci

stages:
  - audit
  - lint
  - test
  - name: deploy
    if: tag=~^v AND repo=brianneisler/firetree

jobs:
  include:
    - stage: audit
      node_js: 14
      os: linux
      script: npm run security:audit
    - stage: lint
      node_js: 14
      os: linux
      script: npm run lint
    - stage: deploy
      node_js: 14
      os: linux
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: me@brianneisler.com
        api_key: '$NPM_TOKEN'
        on:
          tags: true

env:
  global:
    secure: cq7gQh+9/Emaw/2q0ca34pkL0HgWYL4YasM6p9wGsXRlMb8gNHxR3LdWUQIBg9cpi0KdXsOGMSN1gq0NiMi2E+gU0iZmKdSjQYgP0U41UGa8EKLCEoviZ4+TLTwbtKhXAuEtgJD59Kq2sz/8mpFvvV1FviDbYyEKB9RplhVMusz2/8qAMxnBsoD0llo8cVUceSc8NytPLVlvBT0N8Qikj5+pVXGPe2N6ulTDHWQwewh/sFRi5SRU8N2e9QJT8Cgry8PBAe6n/FbK1th+MlMq+1q/4miK0t5e4uD4/xeMyPRznLdTPWO/az1bSImcI6l1V+J7qDWlr1JyIQMyHHybSMGA9aeHfC4RouHM4CHpk76VqV+2N85cyj3zbaSUtNBuOZ9dks4sWgpHiq5SzsCzQeYKYoaRZpTPIWNp+0oQKBTBUx0+QLopHHH0At/9RkPWuamiEjnQCHBT2rVO18WqZDdcKFPaj+FWFRLp76J+W6cvRfqiA0aUcQ/vC/4kJszMeK4+Fnobp/1jNYZq72YHAENfnvflIjhx1RLHpLhe+QAdf2Sa+QJ1b6Pn0ewdZhhagplVGmRkdyHz3C7pJINVr8J/Q1nPX7F93Ib/RdUQTQMummyVcY6dr/HMjx178U3KlcDq0qNfGxbS66BMHAQpmeavwpHvl2BKRUFqZiDn3W0=
